### PR TITLE
Remove console.log's

### PR DESCRIPTION
**Pull request by rstacruz**
It might be a good time to remove these :)

If you prefer, it can be done using [debug](https://yarn.pm/debug), which Gatsby itself uses.

### CODE REVIEW

**Comment by Hebilicious** [comment]
Using debug would be cleaner. Can you make a PR for it ?

**Comment by cupojoe** [comment]
@Hebilicious is there a plan to merge this one soon?

**Comment by Hebilicious** [comment]
I would like to have still some feedback of whether the plug-in is doing something or not. In the meantime I'll merge that in.

**Comment by cupojoe** [comment]
maybe a verbose flag with false by default?

**Comment by shaunbent** [comment]
@Hebilicious are you still keen to merge this? I am also getting a noisy output.

**Comment by ZLevine** [comment]
+1, This is too noisy compared to our other output from `develop`

**Comment by Hebilicious** [comment]
I'm merging it as soon as I get home

**Comment by ZLevine** [comment]
Thanks @Hebilicious ! Looking forward to the release.

**Comment by meechanism** [comment]
Is there a timeframe for when this will be published?

**Comment by shaunbent** [comment]
@Hebilicious Thanks for merging this PR, would it be possible to have this package published.

**Comment by ZLevine** [comment]
Second -- would be great to get this published, thanks!

**Pull request merged**
